;;; Automatically generated by ‘recentf’ on Mon Nov 18 10:04:34 2024.

(setq recentf-list
      '(
        "~/.dotfiles/emacs/.config/emacs/emacs.org"
        "~/org/work-log.org"
        "~/org/todos.org"
        "~/org/todo.org"
        "~/org/projects.org"
        "~/.dotfiles/emacs/.config/emacs/var/bookmark-default.el"
        "~/.config/emacs/var/bookmark-default.el"
        "~/repos/spacelinq/m2mtests/m2m/m2m.c"
        "~/repos/spacelinq/libs/lib.satpaq/higherground.lib.satpaq/src/main/java/higherground/lib/satpaq/satpaq/m2m/SatPaqM2MDriver.java"
        "~/repos/spacelinq/libs/lib.satpaq/higherground.lib.satpaq/proguard-rules.pro"
        "~/repos/spacelinq/README.md"
        "~/repos/spacelinq/m2mtests/CMakeLists.txt"
        "~/repos/ship/vesseljs/examples/garc.html"
        "~/.config/emacs/init.el"
        "~/repos/spacelinq/m2mtests/unittests/crc.h"
        "~/repos/spacelinq/libs/lib.satpaq/higherground.lib.satpaq/src/main/java/higherground/lib/satpaq/satpaq/SatPaqM2M.kt"
        "~/repos/ship/vesseljs/examples/Ship_in_Ocean_still_water.html"
        "~/repos/ship/vesseljs/examples/Hull_Weight.html"
        "~/repos/ship/vesseljs/README.md"
        "~/repos/ship/README.md"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
