;;; Automatically generated by ‘recentf’ on Mon Nov 18 09:21:56 2024.

(setq recentf-list
      '(
        "~/org/todos.org"
        "~/.config/emacs/var/bookmark-default.el"
        "~/.config/emacs/emacs.org"
        "~/.config/sway/config.d/swayfx"
        "~/.config/sway/config.d/output"
        "~/.config/sway/config.d/default"
        "~/.config/sway/config"
        "~/.config/swayr/config.toml"
        "~/.config/sway/config.d/autostart_applications"
        "/etc/skel/.config/sway/config.d/autostart_applications"
        "/etc/skel/.config/sway/scripts/swayfader.py"
        "/etc/skel/.config/sway/config.d/default"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
